### ISSUE TITLE
Data set request

### ISSUE THREAD

**Issue by niranjan8129** [AvinashSingh786/Fraud-Analysis#2]
Hi Avinash ,thank you for updating the model. I like it very much.  could you please update if you execl sheet data set ?

**Comment by AvinashSingh786** [comment]
Hi Niranjan, could you please be more specific, do you want the database to be created as an excel sheet instead of a sqlite?

**Comment by niranjan8129** [comment]
Thanks for your prompt response . I was looking sqllite data set, is it possible export through excel and update ?

**Comment by AvinashSingh786** [comment]
Do you want the sqlite data set to be written to excel sheet or do you want excel sheet to be loaded into sqlite....
I am still not understanding?

**Comment by niranjan8129** [comment]
Do you want the sqlite data set to be written to excel sheet - Yes Brother . Sorry to bother you .
May I know your email address ? my email id - niranjan8129@gmail.com

**Comment by AvinashSingh786** [comment]
I have added a new function that writes to an excel sheet instead of sqlite DB
