### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Rajeswari543** [AvinashSingh786/Fraud-Analysis#3]
please provide the data set . and when your down load the data set

**Comment by AvinashSingh786** [comment]
The dataset is randomly created with the CreateDatabase function so there is no link for a dataset, you can control the amount of data you want since the data is randomly generated. Do you want me to upload my randomly generated dataset?

**Comment by Rajeswari543** [comment]
please add ur data set

**Comment by Rajeswari543** [comment]
please add the relevant train data set and test data set .....

**Comment by AvinashSingh786** [comment]
The training and testing data is from the original database, it is just randomly split with the defacto ratio of 70/30. If you looked at the code you would have known.
