### ISSUE TITLE
please upload what are thing you need to create the projects and some website liks 

### ISSUE THREAD

**Issue by Rajeswari543** [AvinashSingh786/Fraud-Analysis#4]

**Comment by AvinashSingh786** [comment]
I do not understand? Also, please type your message as a description, not as a subject.

If you are asking on how to create a project from the files then, no, they are just scripts that can run out of the box through terminal or command prompt provided the packages are installed.

I simplified the installation process and will be updated on the next commit

**Comment by Rajeswari543** [comment]
please refer one more data set thats related to your coding and project

**Comment by AvinashSingh786** [comment]
I did this some time ago. If you want datasets you will have to find them yourself. This data was randomly created and isn't compared to other datasets.
